### ISSUE TITLE
Null user can be created

### ISSUE THREAD

**Issue by sids911** [simplerisk/bundles#13]
Hi - a new user can be created in the latest version with null values for username and password, while all the privileges can be assigned to this "empty" username user. This "null" user can log in and log out like normal user.

**Comment by jsokol** [comment]
Bryan,

I have created a ticket to track this issue and will hopefully be able 
to verify and generate a fix for it for the next release. Thank you.

Sincerely,

Josh Sokol
CEO of SimpleRisk
http://www.simplerisk.it

**Comment by jsokol** [comment]
This issue has been fixed in the code that will be going out in our next release.
