### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sids911** [simplerisk/bundles#14]
Hi Josh - I really think the simplerisk homepage could be used for something better than just the simplerisk logo PNG file. It feels quite a bit empty right now. 
Maybe even a aggregation of user relevant RSS feeds (that can be configured in the configuration menu?) can be displayed here beneath the large simplerisk logo could be useful here.

**Comment by jsokol** [comment]
We need to be careful with this.  Too much dynamic functionality and you risk introducing vulnerabilities into a page that is relatively static and not protected behind a user/pass.  I've considered using it for updates or announcements, but I don't think that's something that everyone wants to see.  All that said, I will be working on a new design with templating at some point next year which will make it easier for users to customize their instances.  I'm hopeful that will at least get you part of the way to your desired look/feel.
