### ISSUE TITLE
Report tab error

### ISSUE THREAD

**Issue by jtomaski** [simplerisk/bundles#16]
Hi;

After a new installation, I'm seeing the following error on the Reporting tab.

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'simplerisk.a.calculated_risk' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by' in /Library/WebServer/Documents/simplerisk/includes/reporting.php:428 Stack trace: #0 /Library/WebServer/Documents/simplerisk/includes/reporting.php(428): PDOStatement->execute() #1 /Library/WebServer/Documents/simplerisk/reports/index.php(85): open_risk_level_pie('Risk Level') #2 {main} thrown in /Library/WebServer/Documents/simplerisk/includes/reporting.php on line 428

Regards,
Jeff

**Comment by jsokol** [comment]
It looks like the issue that you are running into is that "only_full_group_by " sql mode is enabled, but the application isn't configured to work in that mode.  That's something that I'll need to consider updating and testing for a future release, but for now, here's how to fix it:

1) Run "SELECT @@sql_mode" to see the current SQL modes
2) Remove "only_full_group_by" from the list returned
3) Run "SET sql_mode = '<SQL MODES>'" specifying any other SQL modes that were returned.  If only_full_group_by was the only one returned, then you can leave it as ''

Let me know if that works for you.

~josh

**Comment by jtomaski** [comment]
that totally worked thank you so much!

**Comment by jsokol** [comment]
I'm glad that worked.  I'm closing out this issue, but have a "ToDo" item to look into restructuring the database to work in only_full_group_by mode.  It sounds like they are considering making that the default in MySQL 5.7.  Thank you for bringing this to my attention.
