### ISSUE TITLE
Feature Request - capability to add multiple files to a single risk

### ISSUE THREAD

**Issue by sids911** [simplerisk/bundles#17]
Hi - I believe there should be a capability to add multiple files to a single risk / issue (Supporting Documentation). This would help maintain a trail of all the documentation associated with the risk (emails / documents / spreadsheets etc). Thank you for the good work!

**Comment by jsokol** [comment]
Hello,
I think this is an excellent idea for a feature enhancement.  I just finished the code to allow file attachments for mitigations and I don't think that this will be too difficult to accomplish across both.  I have added this to my roadmap and will do my best to get it done for my next release.
~josh

**Comment by sids911** [comment]
Great! Thank you!

**Comment by jsokol** [comment]
Hello,
Just a quick note to let you know that SimpleRisk 20151219-001 was released today which includes the requested feature.  Please let me know if you have any questions.
~josh
