### ISSUE TITLE
Corrupted theme

### ISSUE THREAD

**Issue by yehias** [simplerisk/bundles#18]
After I installed it and login I see that theme is corrupted not like demo page any suggestions

**Comment by jsokol** [comment]
What browser are you using?  Any plugins or extensions that would block javascript or css?  Is it one page in particular or all of them?  Can you please provide a screenshot?  I will see if I can replicate.  Thank you.

Sincerely,

Josh Sokol
CEO of SimpleRisk
https://www.simplerisk.it


-------- Original Message --------

**Comment by yehias** [comment]
Im using Firefox and I tried it on Google Chrome same issue for screenshot
just give me till Monday and I will send

**Comment by jsokol** [comment]
Ok, sounds good.  I have hundreds of users and this is the first I've heard this so I'm thinking its an environmental issue right now.  I will do my best to help troubleshoot once I have more info.  Thanks.

Sincerely,

Josh Sokol
CEO of SimpleRisk
https://www.simplerisk.it


-------- Original Message --------

**Comment by yehias** [comment]
Thanks a lot in advance

**Comment by jsokol** [comment]
Wondering if you have any more information for me on this?

~josh

**Comment by yehias** [comment]
Hey Josh sorry for late reply consider solved it was Firefox issue
