### ISSUE TITLE
File attachment Download problem

### ISSUE THREAD

**Issue by sids911** [simplerisk/bundles#19]
In the latest version, when I try to download an attachment from a risk, an entirely different file (from a different risk) is downloaded. Steps to reproduce; 
1. I attach files "filenameA.PDF" and "filenameB.XLS" to risk no. 1022
2. Save the risk or update the risk
3. Click on the link showing either "filenameA.PDF" or "filenameB.XLS"
4. The file that is downloaded is not either "filenameA.PDF" or "filenameB.XLS" - it is actually a file that was attached to an entirely different risk (lets call it risk no. 1007)
5. Everytime you try to open the attached file in ANY of the inserted risks, ONLY the file attached in the risk 1007 is downloaded.

I have tried it on Latest Chrome and IE 11. Please let me know if you need additional information. Thanks!

**Comment by jsokol** [comment]
Thank you very much for reporting this bug.  It was reported to me a 
couple of weeks ago and is the result of a change that I made in a 
recent release to allow for the upload of multiple files.  I've fixed it 
in my development version so it will roll out with the next release.  In 
the meantime, however, you can edit the management/download.php page as 
follows:

Remove: $id = (is_numeric($_GET['id']) ? (int)$_GET['id'] : 0);
Replace With: $id = $_GET['id'];

Remove: $id = (is_numeric($_POST['id']) ? (int)$_POST['id'] : 0);
Replace With: $id = $_POST['id'];

So it should end up looking like:

                 if (isset($_GET['id']))
                 {
                      // Set the id to the get parameter
                     $id = $_GET['id'];
                 }
                 else if (isset($_POST['id']))
                 {
                     // Set the id to the post parameter
                    $id = $_POST['id'];
                 }

That should fix it!

~josh

**Comment by sids911** [comment]
Thanks Josh! Do we have timeframe for the next release? I would like to test it, and would rather test the new version instead of the first release of 2016.

**Comment by jsokol** [comment]
I would guess that the next release will be ready in 6-8 weeks.  Currently, I am working on adding a whole new "Risk Assessment" functionality that is a non-trivial exercise.

**Comment by jsokol** [comment]
This issue was resolved in the last release of SimpleRisk.  Please let me know if you have any other issues.
