### ISSUE TITLE
All values imported as Custom Value are changed to 10

### ISSUE THREAD

**Issue by maru37** [simplerisk/bundles#20]
I imported a CSV of about 40 risks this afternoon. Everything went fine on the front end; mapping worked great and I selected the field that each column should map to. When I went in to view the risks I noted that any value that I mapped to "Custom Value" was changed to 10. For example, the following risk had a custom value of "2."

<img width="283" alt="screen shot 2016-06-08 at 3 30 37 pm" src="https://cloud.githubusercontent.com/assets/6939686/15908119/0a608ae4-2d8e-11e6-8ded-1b5922de0427.png">

After import, the value changed to "10." Upon further inspection it seems as though math is not working:

<img width="452" alt="screen shot 2016-06-08 at 3 33 03 pm" src="https://cloud.githubusercontent.com/assets/6939686/15908185/5969c1b4-2d8e-11e6-94ef-7a42521fa42f.png">

Curious indeed. Perhaps it has something to do with the scoring method. My preference is custom because we are using a scoring method not supported natively by the application.

Thanks!

**Comment by jsokol** [comment]
You are spot on with respect to the Scoring Method.  Create a new column and set the value to 5 (ie. Custom Scoring) and import mapping that column to the Scoring Method.  That should do it.

~josh


-------- Original Message --------
