### ISSUE TITLE
Simplerisk Installation in a 000webhost server not working

### ISSUE THREAD

**Issue by igcp** [simplerisk/bundles#21]
Hello!

I'm trying to install simplerisk in a 000webhost website/database and i keep getting errors after errors. 

I sent through ftp the two folders needed for installation of simplerisk.  The bundle files are inside a folder named "simplerisk" and the installation files are inside a folder named "install". (see web.png)

Then, as the simplerisk installation guides says, I navigated to my website \install folder (error1.png) and introduced the database name provided by 000webhost. (see db.png)

As a results of this steps i keep getting an error named "http error 500". 

Is there any help you could provide me on this subject? 

I'm using firefox and windows 7 

Best regards. 

Filipe

![db](https://cloud.githubusercontent.com/assets/24433254/22063188/65559948-dd75-11e6-8057-c120461c6771.png)
![error1](https://cloud.githubusercontent.com/assets/24433254/22063189/6558a1ba-dd75-11e6-9c13-33a6be7df71b.png)
![web](https://cloud.githubusercontent.com/assets/24433254/22063187/655337a2-dd75-11e6-896f-5f326bffcaf7.png)

**Comment by jsokol** [comment]
The install directory should go into the simplerisk directory so that it can find and modify the config.php file.  The Apache error log should show more information about the actual issue you are experiencing.  Do you know what version of MySQL and PHP your 000webhost is running?

**Comment by igcp** [comment]
jsokol, thank you for your reply. Unfortunately i keep not being sucessful in the installation process.

The MySQL version 000webhost is using is 5.1. The PhP version is 7.1. 

Firstly, I inserted the install folder inside the simplerisk folder as you adviced. 

![000web1](https://cloud.githubusercontent.com/assets/24433254/22105117/77197756-de3a-11e6-8f94-30064f7657dd.png)

Then, I navigated to my new website \install folder and filled the needed fields. 
As you can see, the IP field I kept it as localhost.

![login1](https://cloud.githubusercontent.com/assets/24433254/22105227/fc0c60fe-de3a-11e6-8648-b4676a0b8ea7.png)

This has given me the following error: 

![http error](https://cloud.githubusercontent.com/assets/24433254/22105285/3088ef00-de3b-11e6-8417-e3c3817a7c08.png)

Given this, i thought that the host database name might be incorrect. I went to phpmyadmin, inside the data base and run the following query:  

select @@hostname;
    show variables where Variable_name like '%host%';

![phpmy](https://cloud.githubusercontent.com/assets/24433254/22105634/e0794738-de3c-11e6-8ec7-8087ff05c58d.png)

This gave me the following host name:  8472.us-imm-sql1.000webhost.io
Which i used in as database hostname.

![login2](https://cloud.githubusercontent.com/assets/24433254/22105644/f413d07e-de3c-11e6-82ec-afefff037417.png)

Unfortunately, once again i got an error. This is the same error i get if i write a random database host name. 

![error2](https://cloud.githubusercontent.com/assets/24433254/22105667/0e76456e-de3d-11e6-9eff-ab27824abf07.png)

At this moment i run out of ideas (and knowledge, i guess) in order to solve this problem. Which is really unfortanate because in my company we would like to run your risk application. Do you have any more advice in order to solve this problem? 

I recall that we are trying to install simplerisk in windows. I'm not sure if this has any impact on your apache question. We don't know how to see the apache log. 

Thank you.

Best regards.

**Comment by jsokol** [comment]
Unfortunately, SimpleRisk does not currently support PHP 7.x.  Last I checked it was not being recommended for production use and there are known conflicts between the SimpleRisk code and PHP 7.x.  The latest 5.6.29 release should work fine.

If you would like to try out SimpleRisk, we offer a 30 day free trial on our Hosted platform.  We also have several hosting plans that not only ensure a proper environment, but also provide you with backups, monitoring, and all of our Extra functionality.  If you want to host SimpleRisk yourself, then we highly recommend running on Ubuntu 14.04.

~josh


-------- Original Message --------

**Comment by igcp** [comment]
Once again, thank you josh. 

Every possibility that doesn't allow us to install simplerisk in our own servers would not be approved. 

Nevertheless, in order to fully check simplerisk, where can i have access to the 30 days free trial in your host platform? I don't see in simplerisk website that option. Only the demo tab, where i guess all simplerisk features will not be deployed.

**Comment by jsokol** [comment]
I completely understand.  You should see a "Try" button on the main page of the website.  There will be a form that you can fill out from there to do the 30 day trial.  If you plan on hosting it internally, eventually, then I would recommend using Ubuntu 14.04.  It comes with everything that you need to get SimpleRisk running using our installation guide.

~josh


-------- Original Message --------
