### ISSUE TITLE
Edit/Save details not working proper

### ISSUE THREAD

**Issue by radutoma74** [simplerisk/bundles#22]
@jsokol 

I recently update the Simplerisk applications to the latest version, but the Save button does not working when try to edit an existing risk or to add a comment.

My PHP version is 5.6.40.

Thanks

**Comment by jsokol** [comment]
Out of curiosity, are you running Internet Explorer?  If so, can you please try it with Chrome, Firefox, or Edge instead?  We had an issue reported today that we are digging into and this appears to match that description.  Thanks!

**Comment by radutoma74** [comment]
@jsokol 
Initially, I opened the application on Microsoft Edge 42.17134.1.0. Today I tried to open it on Chrome and worked well. 
Thanks for help.
