### ISSUE TITLE
SQL GROUP BY CLAUSE

### ISSUE THREAD

**Issue by doddannad** [simplerisk/bundles#23]
#1055 - Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'osshoa4m_newprojectinfo.com.pd.state_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by doddannad** [comment]
#1055 - Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'osshoa4m_newprojectinfo.com.pd.state_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by


while on Cpanel phpmyadmin

**Comment by jsokol** [comment]
Hello.  We do not support only full group by as the MySQL SQL mode.  You will need to turn that off.

https://simplerisk.freshdesk.com/a/solutions/articles/6000086770
